"""empty message

Revision ID: 403ae0c68d58
Revises: 
Create Date: 2024-11-22 17:25:56.442763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403ae0c68d58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=10), nullable=False),
    sa.Column('coursenum', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('wpi_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('major', sa.String(length=64), nullable=False),
    sa.Column('cum_gpa', sa.Float(), nullable=False),
    sa.Column('grad_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('wpi_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('has_taken', sa.Boolean(), nullable=False),
    sa.Column('been_sa', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['course.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_experience_courseid'), ['courseid'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_experience_userid'), ['userid'], unique=False)

    op.create_table('course_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('number_of_sas', sa.Integer(), nullable=False),
    sa.Column('min_gpa', sa.Float(), nullable=False),
    sa.Column('min_grade', sa.String(length=2), nullable=False),
    sa.Column('prior_experience', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sa_position')
    op.drop_table('course_section')
    with op.batch_alter_table('course_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_experience_userid'))
        batch_op.drop_index(batch_op.f('ix_course_experience_courseid'))

    op.drop_table('course_experience')
    op.drop_table('student')
    op.drop_table('faculty')
    op.drop_table('course')
    # ### end Alembic commands ###
