"""empty message

Revision ID: 7091a093fa3f
Revises: 
Create Date: 2024-11-20 00:20:21.954208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7091a093fa3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('coursenum', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', 'term', 'section', 'coursenum')
    )
    op.create_table('faculty',
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('wpi_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('major', sa.String(length=64), nullable=False),
    sa.Column('cum_gpa', sa.Float(), nullable=False),
    sa.Column('grad_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('wpi_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('number_of_sas', sa.Integer(), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sa_position')
    op.drop_table('course_section')
    op.drop_table('student')
    op.drop_table('faculty')
    op.drop_table('course')
    # ### end Alembic commands ###
