"""Added min_gpa column to sa_position

Revision ID: 8b059d689287
Revises: 
Create Date: 2024-11-20 04:00:30.693575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b059d689287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sa_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_gpa', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('min_grade', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('prior_experience', sa.Boolean(), nullable=False))
        batch_op.drop_column('qualifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sa_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualifications', sa.TEXT(), nullable=False))
        batch_op.drop_column('prior_experience')
        batch_op.drop_column('min_grade')
        batch_op.drop_column('min_gpa')

    # ### end Alembic commands ###
