"""empty message

Revision ID: ffccbc20fc6d
Revises: f7ea38445d68
Create Date: 2024-11-19 19:21:59.833395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffccbc20fc6d'
down_revision = 'f7ea38445d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_code')
        batch_op.drop_column('section_number')
        batch_op.drop_column('instructor_id')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('wpi_id', sa.String(length=9), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sa_position', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('number_of_sas')
        batch_op.drop_column('course_section_id')
        batch_op.drop_column('qualifications')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('wpi_id', sa.String(length=9), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wpi_id')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    with op.batch_alter_table('sa_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualifications', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('course_section_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('number_of_sas', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'course_section', ['course_section_id'], ['id'])

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wpi_id')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('section_number', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('course_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'faculty', ['instructor_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('wpi_id', sa.VARCHAR(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
