name: Run Tests

on:
  push:
    branches:
      - iteration3
  pull_request:
    branches:
      - iteration3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run unittest for models
    # - name: Run unittest for models
    #   run: |
    #     python -m unittest -v tests/test_models.py

    # Run pytest for routes
    - name: Run pytest for routes
      run: |
        python -m pytest -v tests/test_routes.py

    # Set up Selenium dependencies
    - name: Set up Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb firefox firefox-geckodriver
        pip install selenium

    # # Run Selenium tests (run virtual display server first)
    # - name: Run Selenium tests
    #   env:
    #     DISPLAY: ':99'
    #   run: |
    #     Xvfb :99 -screen 0 1920x1080x24 &
    #     python -m unittest -v tests/test_selenium.py
