# Install dependencies
- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt
# Run our unit tests - testing DB model methods
- name: Run unittest tests
run: |
python -m unittest -v ./tests/test_models.py
# Run our unit tests - testing routes
- name: Run pytest unit tests
run: |
python -m pytest -v ./tests/test_routes.py
